-- ============================================================
-- Bastion Block A — Source Catalogue
-- ~95 sources, six categories, all free/public.
-- ============================================================
--
-- Conventions:
--  - source_id is a stable slug; never rename, only deprecate.
--  - priority 1-3 = must-have for Eastern Ladakh demo
--  - priority 4-6 = realism floor raisers
--  - priority 7-9 = nice-to-have / Block B fitting only
--  - rate_limit_seconds: aggressive on news/.gov; generous on archives
-- ============================================================

INSERT INTO bastion_provenance.sources
(source_id, name, category, realism_tier, scrape_class, refresh_cadence, legal_posture,
 base_url, url_pattern, seed_urls, notes, rate_limit_seconds, priority)
VALUES

-- ============================================================
-- CATEGORY 1 — GEO / INFRASTRUCTURE  (terrain, satellite, roads)
-- ============================================================

('bhuvan_lulc',
 'Bhuvan Land Use / Land Cover (ISRO)',
 'geo_infra', 'tier_1_authoritative', 'tile_raster', 'once', 'gov_open_data',
 'https://bhuvan.nrsc.gov.in',
 '/wms?layers=lulc:{state}',
 ARRAY['https://bhuvan-app1.nrsc.gov.in/thematic/thematic/index.php'],
 'WMS endpoint. JK + Ladakh tiles only for Phase 1. Auth-free for viewer; bulk download requires login — use viewer endpoint.',
 5.0, 2),

('bhuvan_terrain_cartosat',
 'Bhuvan Cartosat DEM',
 'geo_infra', 'tier_1_authoritative', 'tile_raster', 'once', 'gov_open_data',
 'https://bhuvan.nrsc.gov.in',
 '/elevation/elevation.php',
 ARRAY['https://bhuvan-app3.nrsc.gov.in/data/download/index.php'],
 '30m DEM. Use for slope/aspect on supply routes. Cartosat preferred over SRTM for India.',
 5.0, 2),

('osm_overpass_ladakh',
 'OpenStreetMap (Overpass API) — Ladakh extract',
 'geo_infra', 'tier_2_credible', 'api_json', 'monthly', 'cc_licensed',
 'https://overpass-api.de',
 '/api/interpreter',
 ARRAY['https://overpass-api.de/api/interpreter'],
 'Roads, passes, helipads, settlements. ODbL — attribute. Query by bbox: Ladakh is approx 32-36N, 75-80E. Single most useful free geo source.',
 2.0, 1),

('osm_planet_india',
 'OpenStreetMap planet extract — India (Geofabrik)',
 'geo_infra', 'tier_2_credible', 'bulk_crawl', 'monthly', 'cc_licensed',
 'https://download.geofabrik.de',
 '/asia/india-latest.osm.pbf',
 ARRAY['https://download.geofabrik.de/asia/india.html'],
 'Full PBF for offline routing. ~1GB. Use osmium to clip to Ladakh bbox.',
 10.0, 3),

('srtm_30m',
 'SRTM 30m global DEM (USGS)',
 'geo_infra', 'tier_1_authoritative', 'tile_raster', 'once', 'public_domain',
 'https://e4ftl01.cr.usgs.gov',
 '/MEASURES/SRTMGL1.003/',
 ARRAY['https://search.earthdata.nasa.gov/'],
 'Backup to Cartosat. Earthdata login is free but required — store creds in .env, do not commit.',
 5.0, 4),

('aster_gdem',
 'ASTER Global DEM v3',
 'geo_infra', 'tier_1_authoritative', 'tile_raster', 'once', 'public_domain',
 'https://lpdaac.usgs.gov',
 '/products/astgtmv003/',
 ARRAY['https://search.earthdata.nasa.gov/'],
 'Higher coverage at high latitudes than SRTM. Use for >60N if needed; for Ladakh, SRTM/Cartosat suffice.',
 5.0, 7),

('sentinel2_copernicus',
 'Sentinel-2 L2A (Copernicus Open Access)',
 'geo_infra', 'tier_1_authoritative', 'api_json', 'weekly', 'gov_open_data',
 'https://catalogue.dataspace.copernicus.eu',
 '/odata/v1/Products',
 ARRAY['https://browser.dataspace.copernicus.eu/'],
 'Free. 10m optical. Snow series for Zoji La / Khardung La / Marsimik La. Build a 10-year pass-by-pass NDSI time series — this is the single highest-value free dataset for the route closure model.',
 3.0, 1),

('landsat_usgs',
 'Landsat 8/9 Collection 2 (USGS)',
 'geo_infra', 'tier_1_authoritative', 'api_json', 'weekly', 'public_domain',
 'https://earthexplorer.usgs.gov',
 '/scene/metadata/full/{scene_id}',
 ARRAY['https://earthexplorer.usgs.gov/'],
 '30m optical. Pre-2015 history (before Sentinel-2). Good for long-baseline glacier/snow trends.',
 3.0, 5),

('modis_snow',
 'MODIS MOD10A1 daily snow cover',
 'geo_infra', 'tier_1_authoritative', 'tile_raster', 'daily', 'public_domain',
 'https://nsidc.org',
 '/data/MOD10A1',
 ARRAY['https://nsidc.org/data/mod10a1/versions/61'],
 '500m daily snow. Coarse but daily — fills temporal gaps in Sentinel-2 (5-day revisit).',
 3.0, 4),

('bro_press_releases',
 'Border Roads Organisation — press releases',
 'geo_infra', 'tier_1_authoritative', 'dynamic_js', 'weekly', 'gov_open_data',
 'https://bro.gov.in',
 '/press-releases',
 ARRAY['https://bro.gov.in/index1.asp?lang=1&linkid=66'],
 'JS-rendered. Closure announcements, project completion, BRO commendation lists (proxy for activity intensity by sector).',
 4.0, 2),

('bro_project_vartak',
 'BRO Project Vartak (Arunachal)',
 'geo_infra', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://bro.gov.in',
 '/projects/vartak',
 ARRAY['https://bro.gov.in/index2.asp?lang=1&slid=2447&sublinkid=1989'],
 'Arunachal. Out of demo scope but useful for cross-validating ontology generality.',
 4.0, 8),

('bro_project_himank',
 'BRO Project Himank (Ladakh)',
 'geo_infra', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://bro.gov.in',
 '/projects/himank',
 ARRAY['https://bro.gov.in/index2.asp?lang=1&slid=2447&sublinkid=1990'],
 'CRITICAL — Himank covers Eastern Ladakh roads incl. Khardung La, Chang La, Marsimik La. Top priority within BRO.',
 4.0, 1),

('bro_project_beacon',
 'BRO Project Beacon (Kashmir)',
 'geo_infra', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://bro.gov.in',
 '/projects/beacon',
 ARRAY['https://bro.gov.in/index2.asp?lang=1&slid=2447&sublinkid=1991'],
 'Beacon owns Zoji La maintenance. Critical for Eastern Ladakh resupply route.',
 4.0, 1),

('bro_project_deepak',
 'BRO Project Deepak (Uttarakhand/HP)',
 'geo_infra', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://bro.gov.in',
 '/projects/deepak',
 ARRAY['https://bro.gov.in/index2.asp?lang=1&slid=2447&sublinkid=1992'],
 'Manali-Leh route. Alt resupply axis to Eastern Ladakh in summer.',
 4.0, 3),

('bro_project_udayak',
 'BRO Project Udayak (Sikkim/Arunachal)',
 'geo_infra', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://bro.gov.in',
 '/projects/udayak',
 ARRAY['https://bro.gov.in/index2.asp?lang=1&slid=2447&sublinkid=1993'],
 'Out of demo scope; keep for ontology breadth.',
 4.0, 8),

('bro_project_setuk',
 'BRO Project Setuk (Sikkim)',
 'geo_infra', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://bro.gov.in',
 '/projects/setuk',
 ARRAY['https://bro.gov.in/index2.asp?lang=1&slid=2447&sublinkid=1994'],
 'Out of demo scope.',
 4.0, 9),

('nhai_road_quality',
 'NHAI road condition reports',
 'geo_infra', 'tier_1_authoritative', 'pdf_document', 'quarterly', 'gov_open_data',
 'https://nhai.gov.in',
 '/reports',
 ARRAY['https://nhai.gov.in/reports'],
 'NH-1 / NH-1A condition. Tangentially relevant — Pathankot-Srinagar feeds into Zoji La axis.',
 5.0, 6),

-- ============================================================
-- CATEGORY 2 — WEATHER & CLOSURES
-- ============================================================

('imd_daily_bulletin',
 'IMD All India Weather Bulletin',
 'weather_closures', 'tier_1_authoritative', 'pdf_document', 'daily', 'gov_open_data',
 'https://mausam.imd.gov.in',
 '/Forecast/marquee_data/{yyyymmdd}_dailyweather.pdf',
 ARRAY['https://mausam.imd.gov.in/responsive/allindiaweatherreport.php'],
 'Daily PDF. Build full 15-year archive. Parse with pdfplumber; tables are consistent post-2015.',
 6.0, 1),

('imd_aws_data',
 'IMD AWS station archives',
 'weather_closures', 'tier_1_authoritative', 'static_html', 'daily', 'gov_open_data',
 'https://aws.imd.gov.in',
 '/AWS_Data_Display.aspx',
 ARRAY['https://aws.imd.gov.in/'],
 'Automated weather stations. Leh is 421820. Hourly data goes back ~10 years for some stations.',
 8.0, 2),

('imd_himalayan_centre',
 'IMD Regional Met Centre — Srinagar/Leh',
 'weather_closures', 'tier_1_authoritative', 'static_html', 'daily', 'gov_open_data',
 'https://mausam.imd.gov.in',
 '/srinagar',
 ARRAY['https://mausam.imd.gov.in/srinagar/'],
 'Regional bulletins. Issue closure forecasts that mainstream press cites verbatim.',
 6.0, 1),

('imd_snowfall_archive',
 'IMD snowfall observation archive',
 'weather_closures', 'tier_1_authoritative', 'pdf_document', 'monthly', 'gov_open_data',
 'https://mausam.imd.gov.in',
 '/snowfall',
 ARRAY['https://mausam.imd.gov.in/snowfall_archive'],
 'Monthly snowfall summaries. Critical training data for pass-closure model.',
 6.0, 2),

('thehindu_archive',
 'The Hindu — archive search',
 'weather_closures', 'tier_3_journalistic', 'bulk_crawl', 'weekly', 'fair_use_research',
 'https://www.thehindu.com',
 '/search/?q={pass_name}+closed',
 ARRAY['https://www.thehindu.com/search/'],
 'Archive 2000-present. Full-text via search. Throttle hard — they rate-limit.',
 10.0, 2),

('indianexpress_archive',
 'Indian Express — archive',
 'weather_closures', 'tier_3_journalistic', 'bulk_crawl', 'weekly', 'fair_use_research',
 'https://indianexpress.com',
 '/?s={query}',
 ARRAY['https://indianexpress.com/section/india/'],
 'Strong on Ladakh defense reporting. Snehesh Alex Philip covered 2020 standoff in detail (now at ThePrint).',
 10.0, 2),

('toi_archive',
 'Times of India — archive',
 'weather_closures', 'tier_3_journalistic', 'bulk_crawl', 'monthly', 'fair_use_research',
 'https://timesofindia.indiatimes.com',
 '/topic/{topic}',
 ARRAY['https://timesofindia.indiatimes.com/topic/zoji-la'],
 'Lower SNR, higher volume. Useful for closure date triangulation.',
 12.0, 4),

('ht_archive',
 'Hindustan Times — archive',
 'weather_closures', 'tier_3_journalistic', 'bulk_crawl', 'monthly', 'fair_use_research',
 'https://www.hindustantimes.com',
 '/search?q={query}',
 ARRAY['https://www.hindustantimes.com/india-news'],
 'Solid defense desk. Rahul Singh byline.',
 10.0, 4),

('tribune_archive',
 'The Tribune (Chandigarh) — archive',
 'weather_closures', 'tier_3_journalistic', 'bulk_crawl', 'weekly', 'fair_use_research',
 'https://www.tribuneindia.com',
 '/archive/{yyyy}/{mm}',
 ARRAY['https://www.tribuneindia.com/news/archive'],
 'Best North India coverage. Strong J&K and Ladakh local reporting. Vijay Mohan defense byline.',
 8.0, 1),

('greaterkashmir_archive',
 'Greater Kashmir — archive',
 'weather_closures', 'tier_3_journalistic', 'bulk_crawl', 'weekly', 'fair_use_research',
 'https://www.greaterkashmir.com',
 '/?s={query}',
 ARRAY['https://www.greaterkashmir.com/'],
 'Local Kashmir paper. Granular Zoji La / Sonamarg / Drass closure reports — often beats national press by days.',
 10.0, 1),

('kashmirobserver_archive',
 'Kashmir Observer — archive',
 'weather_closures', 'tier_3_journalistic', 'bulk_crawl', 'weekly', 'fair_use_research',
 'https://kashmirobserver.net',
 '/?s={query}',
 ARRAY['https://kashmirobserver.net/'],
 'Second local source for triangulation.',
 10.0, 3),

('reachladakh_archive',
 'Reach Ladakh Bulletin',
 'weather_closures', 'tier_3_journalistic', 'static_html', 'weekly', 'fair_use_research',
 'https://reachladakh.com',
 '/news',
 ARRAY['https://reachladakh.com/news'],
 'Local Ladakh paper. Hyper-local news — unmatched for Eastern Ladakh village/road state.',
 8.0, 1),

('theprint_defence',
 'ThePrint — defence section',
 'weather_closures', 'tier_3_journalistic', 'static_html', 'weekly', 'fair_use_research',
 'https://theprint.in',
 '/category/defence/',
 ARRAY['https://theprint.in/category/defence/'],
 'Snehesh Alex Philip + Lt Gen H S Panag bylines. Highest-quality OSINT-lite reporting on Indian Army.',
 8.0, 2),

('archive_org_wayback',
 'Internet Archive Wayback Machine',
 'weather_closures', 'tier_2_credible', 'api_json', 'on_event', 'public_domain',
 'https://web.archive.org',
 '/web/{yyyymmddhhmmss}/{url}',
 ARRAY['https://archive.org/help/wayback_api.php'],
 'Resurrect dead links. Critical for old BRO/PIB/news pages.',
 3.0, 3),

-- ============================================================
-- CATEGORY 3 — ORBAT (Order of Battle)
-- ============================================================

('iiss_military_balance',
 'IISS Military Balance — India chapter',
 'orbat', 'tier_2_credible', 'manual_download', 'once', 'fair_use_research',
 'https://www.iiss.org',
 '/publications/the-military-balance',
 ARRAY['https://www.iiss.org/publications/the-military-balance/'],
 'Annual. Summary tables free; full chapter paywalled. Fair-use the public summary; supplement with Wikipedia.',
 0.0, 2),

('globalsecurity_indianarmy',
 'Globalsecurity.org — Indian Army',
 'orbat', 'tier_4_osint', 'static_html', 'monthly', 'fair_use_research',
 'https://www.globalsecurity.org',
 '/military/world/india/army-orbat.htm',
 ARRAY['https://www.globalsecurity.org/military/world/india/army.htm'],
 'Detailed (and dated) ORBAT. Trust structure not numbers. Cross-validate with Wikipedia.',
 5.0, 2),

('fas_india',
 'Federation of American Scientists — India',
 'orbat', 'tier_2_credible', 'static_html', 'quarterly', 'fair_use_research',
 'https://fas.org',
 '/issues/nuclear-weapons/india',
 ARRAY['https://fas.org/initiative/nuclear-information-project/'],
 'Stronger on nuclear/missile than conventional. Useful for strategic context.',
 5.0, 5),

('orbat_com',
 'Orbat.com / Ravi Rikhye',
 'orbat', 'tier_4_osint', 'static_html', 'quarterly', 'fair_use_research',
 'http://orbat.com',
 '/site/india/',
 ARRAY['http://orbat.com/'],
 'Dated but most detailed Indian Army ORBAT in OSINT. Brigade-level granularity.',
 5.0, 2),

('damiensymon_substack',
 'Damien Symon — OSINT analyst',
 'orbat', 'tier_4_osint', 'static_html', 'weekly', 'fair_use_research',
 'https://detresfa.substack.com',
 '/archive',
 ARRAY['https://detresfa.substack.com/'],
 'Satellite OSINT, India-China LAC focus. High-quality imagery analysis. Twitter feed mirrors most posts.',
 5.0, 1),

('wikipedia_indianarmy',
 'Wikipedia — Indian Army formations',
 'orbat', 'tier_4_osint', 'static_html', 'monthly', 'cc_licensed',
 'https://en.wikipedia.org',
 '/wiki/{formation_name}',
 ARRAY['https://en.wikipedia.org/wiki/Indian_Army',
       'https://en.wikipedia.org/wiki/XIV_Corps_(India)',
       'https://en.wikipedia.org/wiki/Northern_Command_(India)'],
 'Surprisingly granular. Citations link to Bharat Rakshak, Tribune, IDR — follow the chain.',
 3.0, 1),

('bharatrakshak',
 'Bharat Rakshak',
 'orbat', 'tier_4_osint', 'static_html', 'quarterly', 'fair_use_research',
 'https://www.bharat-rakshak.com',
 '/army',
 ARRAY['https://www.bharat-rakshak.com/'],
 'Indian military enthusiast site, ~20 years of accreted data. Trust structure not numbers.',
 5.0, 3),

('indiandefencereview',
 'Indian Defence Review (IDR)',
 'orbat', 'tier_3_journalistic', 'static_html', 'weekly', 'fair_use_research',
 'http://www.indiandefencereview.com',
 '/category/news',
 ARRAY['http://www.indiandefencereview.com/'],
 'Retired officer bylines. Doctrinal context > hard numbers.',
 6.0, 4),

('forceindia',
 'Force magazine',
 'orbat', 'tier_3_journalistic', 'static_html', 'monthly', 'fair_use_research',
 'https://forceindia.net',
 '/category',
 ARRAY['https://forceindia.net/'],
 'Pravin Sawhney editor. Strong China-LAC analysis.',
 6.0, 4),

('sps_landforces',
 'SP''s Land Forces',
 'orbat', 'tier_3_journalistic', 'static_html', 'monthly', 'fair_use_research',
 'https://www.spslandforces.com',
 '/archives.asp',
 ARRAY['https://www.spslandforces.com/'],
 'Trade pub. Useful for new equipment inductions.',
 6.0, 5),

('claws',
 'Centre for Land Warfare Studies (CLAWS)',
 'orbat', 'tier_2_credible', 'static_html', 'monthly', 'fair_use_research',
 'https://www.claws.in',
 '/publication',
 ARRAY['https://www.claws.in/'],
 'Army-affiliated think tank. Doctrine + capability papers.',
 5.0, 3),

('idsa_manohar_parrikar',
 'MP-IDSA (Manohar Parrikar Inst for Defence Studies)',
 'orbat', 'tier_2_credible', 'static_html', 'monthly', 'fair_use_research',
 'https://www.idsa.in',
 '/publication',
 ARRAY['https://www.idsa.in/'],
 'MoD-funded. Higher-quality strategic analysis.',
 5.0, 3),

('vifindia',
 'Vivekananda International Foundation',
 'orbat', 'tier_2_credible', 'static_html', 'monthly', 'fair_use_research',
 'https://www.vifindia.org',
 '/articles',
 ARRAY['https://www.vifindia.org/'],
 'NSA-adjacent think tank. Strategic, not operational.',
 5.0, 6),

('orfonline_strategic',
 'ORF — Strategic Studies',
 'orbat', 'tier_2_credible', 'static_html', 'weekly', 'fair_use_research',
 'https://www.orfonline.org',
 '/research/strategic-studies',
 ARRAY['https://www.orfonline.org/research/strategic-studies/'],
 'Volume + breadth. Mix doctrine and OSINT.',
 5.0, 5),

-- ============================================================
-- CATEGORY 4 — SCALES OF ISSUE & DOCTRINE
-- ============================================================

('rti_online',
 'RTI Online portal',
 'scales_doctrine', 'tier_1_authoritative', 'manual_download', 'on_event', 'gov_open_data',
 'https://rtionline.gov.in',
 '/',
 ARRAY['https://rtionline.gov.in/'],
 'File RTIs. ~₹10/req. Targets: scales of issue (high-altitude rations, fuel allowances), unit strength returns, ARSP closure data.',
 0.0, 2),

('cic_decisions',
 'Central Information Commission — orders',
 'scales_doctrine', 'tier_1_authoritative', 'pdf_document', 'weekly', 'gov_open_data',
 'https://cic.gov.in',
 '/decisions',
 ARRAY['https://cic.gov.in/cic-decisions'],
 'Many MoD RTI denials are appealed to CIC. CIC orders sometimes attach the disclosed document. Goldmine for scale-of-issue references.',
 5.0, 2),

('factly_rti_archive',
 'Factly — RTI disclosure archive',
 'scales_doctrine', 'tier_2_credible', 'static_html', 'weekly', 'cc_licensed',
 'https://factly.in',
 '/category/rti',
 ARRAY['https://factly.in/category/rti/'],
 'Civil society aggregator. Republishes interesting CIC orders with context.',
 5.0, 3),

('cag_audit_reports',
 'Comptroller & Auditor General — defence reports',
 'scales_doctrine', 'tier_1_authoritative', 'pdf_document', 'quarterly', 'gov_open_data',
 'https://cag.gov.in',
 '/en/audit-report?dept=Defence',
 ARRAY['https://cag.gov.in/en/audit-report'],
 'CRITICAL — CAG defence audits are the most detailed open source on actual procurement, vehicle holdings, fuel consumption, ration scales. Search for "Performance Audit on Provisioning", "Logistic support to forward areas", "Mountain warfare". Build full archive 2010-present.',
 4.0, 1),

('cag_compliance_reports',
 'CAG compliance reports — Army',
 'scales_doctrine', 'tier_1_authoritative', 'pdf_document', 'quarterly', 'gov_open_data',
 'https://cag.gov.in',
 '/en/audit-report/compliance',
 ARRAY['https://cag.gov.in/en/audit-report/compliance/Army'],
 'Compliance reports often disclose specific consumption / wastage figures.',
 4.0, 1),

('prsindia_defence',
 'PRS Legislative Research — Defence',
 'scales_doctrine', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://prsindia.org',
 '/policy/defence',
 ARRAY['https://prsindia.org/policy/defence'],
 'Clean structure. Summarizes parliamentary committee reports — easier than reading raw PDFs.',
 3.0, 2),

('loksabha_committees',
 'Lok Sabha — Standing Committee on Defence',
 'scales_doctrine', 'tier_1_authoritative', 'pdf_document', 'quarterly', 'gov_open_data',
 'https://loksabha.nic.in',
 '/Committee/CommitteeInformation.aspx?comm_code=15',
 ARRAY['https://loksabha.nic.in/Committee/CommitteeInformation.aspx?comm_code=15'],
 'Reports name specific procurement gaps, AOC stockholding shortfalls, EME deadlining percentages. Goldmine.',
 5.0, 1),

('rajyasabha_questions',
 'Rajya Sabha unstarred questions — defence',
 'scales_doctrine', 'tier_1_authoritative', 'pdf_document', 'weekly', 'gov_open_data',
 'https://rajyasabha.nic.in',
 '/rsnew/Questions/qsearch.aspx',
 ARRAY['https://rsdebate.nic.in/'],
 'Numerical answers tabled in Parliament. Vehicle strength, manning, ration provisioning by sector — sometimes redacted, often not.',
 5.0, 1),

('loksabha_questions',
 'Lok Sabha unstarred questions — defence',
 'scales_doctrine', 'tier_1_authoritative', 'pdf_document', 'weekly', 'gov_open_data',
 'http://loksabhaph.nic.in',
 '/Questions/Qsearch15.aspx',
 ARRAY['http://loksabhaph.nic.in/Questions/Qsearch15.aspx'],
 'Same intent, Lok Sabha side. Often more granular than RS.',
 5.0, 1),

('mod_annual_report',
 'Ministry of Defence — Annual Report',
 'scales_doctrine', 'tier_1_authoritative', 'pdf_document', 'once', 'gov_open_data',
 'https://www.mod.gov.in',
 '/dod/annual-reports',
 ARRAY['https://www.mod.gov.in/dod/annual-reports'],
 'Annual. Manning, equipment, infra spend by year. Build 2010-2025 archive.',
 4.0, 2),

('dpp_dap',
 'Defence Acquisition Procedure (DAP 2020) + amendments',
 'scales_doctrine', 'tier_1_authoritative', 'pdf_document', 'on_event', 'gov_open_data',
 'https://www.mod.gov.in',
 '/dod/sites/default/files/dap2030.pdf',
 ARRAY['https://www.mod.gov.in/dod/dap-2020'],
 'Reference doc. Rare but useful for procurement timelines on equipment.',
 0.0, 4),

('quartermaster_manuals_rti',
 'Quartermaster manuals — via RTI / CIC orders',
 'scales_doctrine', 'tier_1_authoritative', 'manual_download', 'on_event', 'gov_open_data',
 'https://cic.gov.in',
 '/decisions',
 ARRAY['https://cic.gov.in/'],
 'Specific CIC orders have released QM scale-of-issue tables. Search: "scale of issue" "high altitude" "ration" "fuel".',
 0.0, 1),

('army_vacancy_notifications',
 'Indian Army recruitment notifications',
 'scales_doctrine', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://joinindianarmy.nic.in',
 '/Notifications.aspx',
 ARRAY['https://joinindianarmy.nic.in/'],
 'Recruitment ratios proxy unit strength changes. Niche.',
 5.0, 7),

('dgmo_briefings',
 'DGMO press briefings (via PIB)',
 'scales_doctrine', 'tier_1_authoritative', 'static_html', 'on_event', 'gov_open_data',
 'https://pib.gov.in',
 '/searchresults.aspx?q=DGMO',
 ARRAY['https://pib.gov.in/'],
 'Rare but high-value. Operational tempo signal.',
 5.0, 4),

-- ============================================================
-- CATEGORY 5 — VEHICLES & EQUIPMENT
-- ============================================================

('tata_motors_defence',
 'Tata Motors Defence — product pages',
 'vehicles_equipment', 'tier_2_credible', 'static_html', 'quarterly', 'fair_use_research',
 'https://www.tatamotors.com',
 '/defence',
 ARRAY['https://www.tatamotors.com/defence/'],
 'Stallion, LPTA series specs. Payload, tare, fuel cons, gradeability — all OEM-published.',
 5.0, 2),

('ashok_leyland_defence',
 'Ashok Leyland Defence',
 'vehicles_equipment', 'tier_2_credible', 'static_html', 'quarterly', 'fair_use_research',
 'https://www.ashokleyland.com',
 '/defence',
 ARRAY['https://www.ashokleyland.com/in/en/defence'],
 'Stallion 4x4/6x6, Topchi, FAT specs. Same justification as Tata.',
 5.0, 2),

('mahindra_defence',
 'Mahindra Defence',
 'vehicles_equipment', 'tier_2_credible', 'static_html', 'quarterly', 'fair_use_research',
 'https://www.mahindradefence.com',
 '/products',
 ARRAY['https://www.mahindradefence.com/'],
 'Light vehicles — ALSV, MPV. Less relevant to bulk resupply, more to QRT/admin.',
 5.0, 5),

('beml_products',
 'BEML — Defence products',
 'vehicles_equipment', 'tier_1_authoritative', 'static_html', 'quarterly', 'gov_open_data',
 'https://www.bemlindia.in',
 '/defence',
 ARRAY['https://www.bemlindia.in/'],
 'Tatra series (heavy), recovery vehicles. PSU — annual reports disclose order books.',
 5.0, 3),

('beml_annual_reports',
 'BEML — annual reports',
 'vehicles_equipment', 'tier_1_authoritative', 'pdf_document', 'once', 'gov_open_data',
 'https://www.bemlindia.in',
 '/investor-relations/annual-reports',
 ARRAY['https://www.bemlindia.in/'],
 'PSU listing — annual report discloses defence order book values. Backs out approx vehicle deliveries.',
 5.0, 3),

('cag_vehicle_audits',
 'CAG audits — Army vehicle fleet',
 'vehicles_equipment', 'tier_1_authoritative', 'pdf_document', 'quarterly', 'gov_open_data',
 'https://cag.gov.in',
 '/en/audit-report?q=vehicle',
 ARRAY['https://cag.gov.in/'],
 'Subset of CAG defence audits specifically on vehicle deadline %, EME workshop performance, spares availability.',
 4.0, 1),

('eme_corps_archive',
 'Corps of EME — public material',
 'vehicles_equipment', 'tier_2_credible', 'static_html', 'quarterly', 'gov_open_data',
 'https://indianarmy.nic.in',
 '/Site/FormTemplete/frmTempSimple.aspx?MnId=N5K%2btf%2fT4uo%3d',
 ARRAY['https://indianarmy.nic.in/'],
 'Limited but doctrinal — tells you what EME considers normal vs deadlined.',
 5.0, 6),

('aoc_corps_public',
 'Army Ordnance Corps — public material',
 'vehicles_equipment', 'tier_2_credible', 'static_html', 'quarterly', 'gov_open_data',
 'https://indianarmy.nic.in',
 '/Site/FormTemplete/frmTempSimple.aspx?MnId=AOC',
 ARRAY['https://indianarmy.nic.in/'],
 'AOC depot listings (Central Ordnance Depots).',
 5.0, 4),

('asc_corps_public',
 'Army Service Corps — public material',
 'vehicles_equipment', 'tier_2_credible', 'static_html', 'quarterly', 'gov_open_data',
 'https://indianarmy.nic.in',
 '/Site/FormTemplete/frmTempSimple.aspx?MnId=ASC',
 ARRAY['https://indianarmy.nic.in/'],
 'ASC composite platoons, supply/transport doctrine.',
 5.0, 4),

('ofb_munitions_india',
 'Munitions India / Yantra India / AVNL etc.',
 'vehicles_equipment', 'tier_1_authoritative', 'static_html', 'quarterly', 'gov_open_data',
 'https://munitionsindia.in',
 '/products',
 ARRAY['https://munitionsindia.in/',
       'https://yantraindia.co.in/',
       'https://avnl.co.in/'],
 'OFB successor PSUs. Product catalogues = ammo SKUs.',
 5.0, 3),

-- ============================================================
-- CATEGORY 6 — TEMPO SIGNALS  (PIB, official press, exercises)
-- ============================================================

('pib_defence',
 'PIB — Defence ministry releases',
 'tempo_signals', 'tier_1_authoritative', 'static_html', 'daily', 'gov_open_data',
 'https://pib.gov.in',
 '/AllReleasem.aspx?MinCode=20',
 ARRAY['https://pib.gov.in/PressReleasePage.aspx?PRID=Defence'],
 'CRITICAL daily pull. Exercise announcements, equipment inductions, casualty acknowledgments — primary tempo proxy.',
 4.0, 1),

('pib_pmindia',
 'PIB — PMO releases (defence-tagged)',
 'tempo_signals', 'tier_1_authoritative', 'static_html', 'daily', 'gov_open_data',
 'https://pib.gov.in',
 '/AllReleasem.aspx?MinCode=53',
 ARRAY['https://pib.gov.in/'],
 'PM visits to forward areas, foundation stones — political tempo signals.',
 4.0, 3),

('mod_press_releases',
 'MoD direct press releases',
 'tempo_signals', 'tier_1_authoritative', 'static_html', 'daily', 'gov_open_data',
 'https://www.mod.gov.in',
 '/dod/whats-new',
 ARRAY['https://www.mod.gov.in/dod/whats-new'],
 'Often duplicates PIB; sometimes earlier.',
 4.0, 3),

('addgpi_twitter_archive',
 'ADG PI (Army spokesperson) — public archive',
 'tempo_signals', 'tier_1_authoritative', 'manual_download', 'weekly', 'fair_use_research',
 'https://twitter.com',
 '/adgpi',
 ARRAY['https://twitter.com/adgpi'],
 'Twitter scraping is broken in 2026 without paid API. Use nitter mirrors + archive.org snapshots.',
 0.0, 4),

('northerncomd_archive',
 'HQ Northern Command — public statements',
 'tempo_signals', 'tier_1_authoritative', 'static_html', 'monthly', 'gov_open_data',
 'https://indianarmy.nic.in',
 '/Site/FormTemplete/frmTemp1PLgrp1C.aspx?MnId=NC',
 ARRAY['https://indianarmy.nic.in/'],
 'XIV Corps falls under Northern Command. Promotional/visit press = tempo proxy.',
 5.0, 2),

('xivcorps_mentions',
 'XIV Corps mentions — multi-source aggregate',
 'tempo_signals', 'tier_2_credible', 'static_html', 'weekly', 'fair_use_research',
 'https://indianarmy.nic.in',
 '/{xiv_corps_keyword}',
 ARRAY['https://www.google.com/search?q=%22XIV+Corps%22+OR+%22Fire+%26+Fury%22'],
 'Aggregator — search across sources for XIV Corps / Fire & Fury Corps mentions.',
 8.0, 2),

('exercise_announcements',
 'Bilateral/multilateral exercises with India',
 'tempo_signals', 'tier_2_credible', 'static_html', 'monthly', 'gov_open_data',
 'https://pib.gov.in',
 '/searchresults.aspx?q=exercise',
 ARRAY['https://pib.gov.in/'],
 'Yudh Abhyas, Hand-in-Hand, Shakti, etc. Exercise calendar = training tempo proxy.',
 5.0, 3),

('mea_briefings',
 'MEA — official briefings on India-China LAC',
 'tempo_signals', 'tier_1_authoritative', 'static_html', 'weekly', 'gov_open_data',
 'https://www.mea.gov.in',
 '/media-briefings.htm',
 ARRAY['https://www.mea.gov.in/media-briefings.htm'],
 'Rare LAC commentary. Spike frequency = strategic tempo.',
 4.0, 4),

('parliament_questions_lac',
 'Parliament questions tagged LAC/Ladakh',
 'tempo_signals', 'tier_1_authoritative', 'pdf_document', 'weekly', 'gov_open_data',
 'http://loksabhaph.nic.in',
 '/Questions/Qsearch15.aspx?q=Ladakh',
 ARRAY['http://loksabhaph.nic.in/Questions/Qsearch15.aspx'],
 'Subset of Parliament questions filtered for tempo signals.',
 5.0, 3),

-- ============================================================
-- CATEGORY 7 — META / OPS  (smaller cluster; archival, dedupe)
-- ============================================================

('commoncrawl_india',
 'Common Crawl — India domain index',
 'tempo_signals', 'tier_4_osint', 'bulk_crawl', 'monthly', 'public_domain',
 'https://index.commoncrawl.org',
 '/CC-MAIN-{yyyy-ww}-index?url=*.in',
 ARRAY['https://commoncrawl.org/'],
 'Resurrect deleted .gov.in / .nic.in pages. Niche but free.',
 0.0, 7),

('gdelt_india',
 'GDELT — India events database',
 'tempo_signals', 'tier_2_credible', 'api_json', 'daily', 'public_domain',
 'https://api.gdeltproject.org',
 '/api/v2/doc/doc?query={query}',
 ARRAY['https://www.gdeltproject.org/'],
 'Pre-tagged geopolitical events. Useful for cross-checking tempo.',
 2.0, 4),

('acleddata_india',
 'ACLED — India conflict data',
 'tempo_signals', 'tier_2_credible', 'api_json', 'weekly', 'cc_licensed',
 'https://api.acleddata.com',
 '/acled/read?country=India',
 ARRAY['https://acleddata.com/'],
 'Free with registration. Fatality + incident dataset. Good for triangulating LoC/LAC incidents.',
 2.0, 4);
