"""
Project Bastion — Stage 2: Incremental World Advancement (#8, v1.0)

Refactors the world from batch-only to LIVE: `advance_one_day(state)` steps
the synthetic world one day past the canonical horizon (2024-12-31), so the
daily tick re-plans a moving world instead of a frozen snapshot.

DESIGN — canonical history + deterministic continuation
────────────────────────────────────────────────────────
The committed seed-42 world through END_DATE stays byte-identical — every
published metric stands. Days AFTER it are generated by this stepper using
the SAME per-day physics functions the batch generator uses
(draw_consumption, climatological_day, daily_hazard_increment, the stock
accounting identity, the closure regimes), with DAY-SEEDED RNG:

    rng(domain, date) = default_rng([42, date.toordinal(), domain_id])

Day-seeding gives three properties batch streams can't:
  • deterministic     — advancing to 2025-03-01 always yields the same world
  • restart-safe      — kill the process, re-init, fast-forward: identical
  • order-independent — 45 days + 45 days ≡ 90 days in one call

BOUNDARY STATE (what carries across 2024-12-31)
  • closing stock per (post, SKU)         — from committed stock_daily
  • active pass closures                  — Zoji La's winter closure SPANS the
    boundary (closes ~Dec 23, reopens spring); read from pass_closures and
    carried. Winter 2024-25 closures are NOT resampled. Fresh sampling starts
    with winter 2025-26.
  • brigade tempo                         — last committed tempo state
  • vehicles in repair at the boundary    — events with return_date > END_DATE
  • vehicle hazard clocks                 — fresh Exp(1) thresholds, cum=0.
    The hazard process is MEMORYLESS (Exp(1) threshold, linear accumulation),
    so this is distributionally exact, not an approximation.
  • per-vehicle band mixes / duty factors — replayed exactly: they are the
    first draws on the seed-42 stream (draw_vehicle_band_mixes then
    draw_duty_intensities), so the continuation uses the SAME persistent
    vehicle identities the canonical history used.

DOCUMENTED SIMPLIFICATIONS (continuation only, all SYNTHETIC-INFERRED)
  • AWS targets for years > 2024 carry the 2024 targets forward (stocking
    norms are sticky year-to-year; no public per-year deltas to anchor).
  • AWS pacing uses remaining-candidate-day count without isolation
    foreknowledge (the batch precounts open days with full hindsight; a
    live system cannot — this is MORE realistic, not less).
  • Routine convoys in transit at the boundary are dropped (their latency
    is 1-3 days; effect is a one-time ripple in the first continuation week).
  • Perishable substitution uses the isolation-gated rule (isolated ⇒ fresh
    demand routes to substitute) without the batch's adaptation decay curve.
  • Weather AR(1) noise state initialises at 0 (one-day transient).

OUTPUTS
  state.json + stock_state.parquet in WORLD_STATE_DIR after each advance;
  per-day rows appended to live_*.parquet; `materialize_live_data()` builds
  a complete Stage-3-ready data dir (base ∪ continuation) so downstream
  stages run unchanged with BASTION_DATA_DIR pointed at it.

Every continuation row carries provenance: generator="advance_v1",
day_seed=[42, ordinal, domain].
"""

from __future__ import annotations

import json
import shutil
from datetime import date, timedelta
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

from config import (
    SEED, START_DATE, END_DATE,
    PASSES, ALTITUDE_BANDS,
    TEMPO_LEVELS, TEMPO_TRANSITION_PROBS_DAILY,
    DAILY_TEMP_NOISE_SIGMA, DAILY_TEMP_NOISE_WINTER_BOOST, DAILY_TEMP_PERSISTENCE,
    WD_EVENTS_PER_WINTER_LAMBDA, WD_EVENT_DURATION_DAYS,
    WD_EVENT_PRECIP_MULT, WD_EVENT_TEMP_DROP_C,
    SNOW_EVENT_THRESHOLD_MM, SNOW_EVENT_CLOSURE_BOOST,
    SPOILAGE_DAILY_FRACTION_PERISHABLE, PERISHABLE_SUBSTITUTE_MAP,
    STOCKOUT_RATIONING_THRESHOLD_DAYS,
    ROUTINE_CONVOY_MIN_GAP_DAYS, POL_CONVOY_MIN_GAP_DAYS,
    ROUTINE_CONVOY_DISPATCH_GAP_DAYS, ROUTINE_RECEIPT_CONVOY_LATENCY_DAYS,
    ROUTINE_RECEIPT_REFILL_TO_COVERAGE_DAYS, POL_CONVOY_MAX_REFILL_COVERAGE_DAYS,
    AWS_SEASON_MONTHS,
    MISSIONS_PER_MONTH_OPEN, MISSIONS_PER_MONTH_WINTER,
    REPAIR_TIME_DEPOT_DAYS, REPAIR_TIME_FIELD_DAYS, DEADLINE_REQUIRES_DEPOT_PROB,
)
from world import build_world, World
from weather import assign_anchors, get_anchor, climatological_day
from consumption import (draw_consumption, compute_isolation_per_post_day,
                          simulate_tempo_trajectory)  # noqa: F401 (parity import)
from vehicles import (draw_vehicle_band_mixes, draw_duty_intensities,
                       daily_hazard_increment, sample_event_threshold)
from stock import _is_perishable, _days_in_month

ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
WORLD_STATE_DIR = ROOT / "world_state"

GENERATOR_TAG = "advance_v1"

# Domain ids for day-seeded RNG streams — stable, documented
_DOMAIN = {"weather": 1, "wd": 2, "closure": 3, "tempo": 4,
           "consumption": 5, "stock": 6, "vehicle": 7}


def _rng(domain: str, d: date) -> np.random.Generator:
    return np.random.default_rng([SEED, d.toordinal(), _DOMAIN[domain]])


def _rng_year(domain: str, year: int) -> np.random.Generator:
    """Year-scoped stream (seasonal closures, WD season events)."""
    return np.random.default_rng([SEED, year, 9000 + _DOMAIN[domain]])


# ═════════════════════════════════════════════════════════════════════════════
# State
# ═════════════════════════════════════════════════════════════════════════════
class WorldState:
    """Everything the one-day step needs to remember. JSON + one parquet."""

    def __init__(self):
        self.sim_date: date = END_DATE              # last COMPLETED day
        self.stock: Dict[Tuple[str, str], float] = {}
        self.pending: Dict[Tuple[str, str], List[Tuple[str, float]]] = {}
        self.last_convoy: Dict[Tuple[str, str], str] = {}
        self.aws_year: int = END_DATE.year
        self.aws_remaining: Dict[Tuple[str, str], float] = {}
        self.noise_state: Dict[str, float] = {}
        self.tempo: str = "normal"
        # active closures: list of {pass_name, end_date(iso), closure_type}
        self.active_closures: List[dict] = []
        # winters already sampled for seasonal passes: {pass_name: [yr,...]}
        self.sampled_winters: Dict[str, List[int]] = {}
        # scheduled future seasonal closures: {pass_name: [(start,end,type)]}
        self.future_closures: List[dict] = []
        # WD events: active + sampled-season registry
        self.wd_active: List[dict] = []
        self.wd_sampled_seasons: List[int] = []
        self.wd_future: List[dict] = []
        # vehicles: {vid: {cum, thr, repair_until(iso|None)}}
        self.veh: Dict[str, dict] = {}

    # ── persistence ─────────────────────────────────────────────────────────
    def save(self, dir_: Path = WORLD_STATE_DIR):
        dir_.mkdir(exist_ok=True, parents=True)
        stock_df = pd.DataFrame(
            [{"post_id": p, "sku": k, "closing_stock": v,
              "pending": json.dumps(self.pending.get((p, k), [])),
              "last_convoy": self.last_convoy.get((p, k)),
              "aws_remaining": self.aws_remaining.get((p, k), 0.0)}
             for (p, k), v in sorted(self.stock.items())])
        stock_df.to_parquet(dir_ / "stock_state.parquet", index=False)
        meta = {
            "sim_date": self.sim_date.isoformat(),
            "aws_year": self.aws_year,
            "noise_state": self.noise_state,
            "tempo": self.tempo,
            "active_closures": self.active_closures,
            "sampled_winters": self.sampled_winters,
            "future_closures": self.future_closures,
            "wd_active": self.wd_active,
            "wd_sampled_seasons": self.wd_sampled_seasons,
            "wd_future": self.wd_future,
            "veh": self.veh,
            "generator": GENERATOR_TAG, "seed": SEED,
        }
        (dir_ / "state.json").write_text(json.dumps(meta, indent=1))

    @classmethod
    def load(cls, dir_: Path = WORLD_STATE_DIR) -> "WorldState":
        st = cls()
        meta = json.loads((dir_ / "state.json").read_text())
        st.sim_date = date.fromisoformat(meta["sim_date"])
        st.aws_year = meta["aws_year"]
        st.noise_state = meta["noise_state"]
        st.tempo = meta["tempo"]
        st.active_closures = meta["active_closures"]
        st.sampled_winters = meta["sampled_winters"]
        st.future_closures = meta["future_closures"]
        st.wd_active = meta["wd_active"]
        st.wd_sampled_seasons = meta["wd_sampled_seasons"]
        st.wd_future = meta["wd_future"]
        st.veh = meta["veh"]
        sdf = pd.read_parquet(dir_ / "stock_state.parquet")
        for _, r in sdf.iterrows():
            key = (r["post_id"], r["sku"])
            st.stock[key] = float(r["closing_stock"])
            st.pending[key] = [tuple(x) for x in json.loads(r["pending"])]
            if r["last_convoy"] is not None and not pd.isna(r["last_convoy"]):
                st.last_convoy[key] = r["last_convoy"]
            st.aws_remaining[key] = float(r["aws_remaining"])
        return st


# ═════════════════════════════════════════════════════════════════════════════
# Static context (loaded once per process)
# ═════════════════════════════════════════════════════════════════════════════
class Ctx:
    def __init__(self, data_dir: Path = DATA_DIR):
        self.world: World = build_world(seed=SEED)
        self.posts = self.world.posts.set_index("id")
        self.skus = self.world.skus.set_index("sku")
        self.anchors = assign_anchors(self.world.posts).set_index("post_id")["anchor_name"]
        # AWS targets: carry the latest committed winter-year forward
        aws = pd.read_parquet(data_dir / "aws_plan.parquet")
        latest = aws["winter_year"].max()
        a = aws[aws["winter_year"] == latest]
        self.aws_target = a.set_index(["post_id", "sku"])["aws_target_qty"].to_dict()
        self.rate = a.set_index(["post_id", "sku"])["winter_daily_rate_mean"].to_dict()
        self.plan_days = a.set_index(["post_id", "sku"])["planning_days"].to_dict()
        # vehicle persistent identities — replayed exactly (first draws on the
        # seed-42 stream, identical to what the batch consumed)
        vr = np.random.default_rng(SEED)
        self.band_mix = draw_vehicle_band_mixes(vr, self.world.vehicles, self.world.posts)
        self.duty = draw_duty_intensities(vr, self.world.vehicles)
        self.vehicles = self.world.vehicles.set_index("vehicle_id")
        self.all_passes = list(PASSES.keys())
        # pass -> config
        self.pass_cfg = PASSES
        # rep-post map for stochastic closures (mirrors disruption.py)
        self.rep_posts = {
            "rear_admin": ["P001", "P002"], "nubra_axis": ["P017"],
            "pangong_axis": ["P003", "P008", "P018"],
            "chushul_demchok": ["P005", "P020", "P022"],
            "hot_springs_galwan": ["P027", "P028", "P030"],
        }


# ═════════════════════════════════════════════════════════════════════════════
# State initialisation from the canonical boundary
# ═════════════════════════════════════════════════════════════════════════════
def init_state(ctx: Ctx, data_dir: Path = DATA_DIR) -> WorldState:
    st = WorldState()
    st.sim_date = END_DATE

    # stock: last committed day
    sd = pd.read_parquet(data_dir / "stock_daily.parquet",
                          columns=["post_id", "sku", "date", "closing_stock"])
    sd["date"] = pd.to_datetime(sd["date"]).dt.date
    last = sd[sd["date"] == END_DATE]
    for _, r in last.iterrows():
        st.stock[(r["post_id"], r["sku"])] = float(r["closing_stock"])

    # AWS: new-year remaining initialises on Jan 1 inside the step
    st.aws_year = END_DATE.year
    st.aws_remaining = {}

    # weather noise per post
    st.noise_state = {pid: 0.0 for pid in ctx.posts.index}

    # tempo: last committed value
    tempo = pd.read_parquet(data_dir / "tempo_daily.parquet")
    tempo["date"] = pd.to_datetime(tempo["date"]).dt.date
    st.tempo = str(tempo.sort_values("date").iloc[-1]["tempo_level"])

    # closures spanning the boundary + winter-2024-25 already sampled in batch
    cl = pd.read_parquet(data_dir / "pass_closures.parquet")
    cl["start_date"] = pd.to_datetime(cl["start_date"]).dt.date
    cl["end_date"] = pd.to_datetime(cl["end_date"]).dt.date
    # The batch CLIPS closures to the simulation range, so a winter closure
    # in progress at END_DATE is recorded as "ending" on END_DATE. Reconstruct
    # the true end from the pass's climatological duration prior (BRO reopen
    # dates cluster around the mean — Zoji La reopens in spring, not Jan 1).
    spanning = cl[cl["end_date"] >= END_DATE]
    for _, c in spanning.iterrows():
        end = c["end_date"]
        if end == END_DATE and c["closure_type"] == "seasonal":
            pcfg = ctx.pass_cfg.get(c["pass_name"], {})
            dur = int(pcfg.get("closure_duration_days_mean", 0))
            if dur > 0:
                end = c["start_date"] + timedelta(days=dur)
        if end > END_DATE:
            st.active_closures.append({"pass_name": c["pass_name"],
                                        "end_date": end.isoformat(),
                                        "closure_type": str(c["closure_type"])})
    # Winter season already covered by batch sampling: 2024-25 for seasonal
    # passes (their closure windows were drawn in the batch run, including
    # the spanning ones we just carried).
    for pname, pcfg in ctx.pass_cfg.items():
        if pcfg.get("closure_regime") == "seasonal":
            st.sampled_winters[pname] = [END_DATE.year]  # winter 2024-25 done
    st.wd_sampled_seasons = [END_DATE.year]              # WD winter 2024-25:
    # batch sampled its events; any extending past Dec 31 are rare and short
    # (≤4 days) — dropped, documented.

    # vehicles: memoryless restart; carry only in-repair-at-boundary
    ev = pd.read_parquet(data_dir / "vehicle_events.parquet")
    ev["return_date"] = pd.to_datetime(ev["return_date"]).dt.date
    in_repair = ev[ev["return_date"] > END_DATE].set_index("vehicle_id")["return_date"]
    rt = np.random.default_rng([SEED, END_DATE.toordinal(), _DOMAIN["vehicle"], 77])
    for vid in ctx.vehicles.index:
        st.veh[vid] = {
            "cum": 0.0,
            "thr": float(rt.exponential(1.0)),
            "repair_until": in_repair[vid].isoformat() if vid in in_repair.index else None,
        }
    return st


# ═════════════════════════════════════════════════════════════════════════════
# One-day step
# ═════════════════════════════════════════════════════════════════════════════
def advance_one_day(ctx: Ctx, st: WorldState) -> dict:
    """Advance the world to st.sim_date + 1. Returns {table: [rows]} for the
    day. Mutates st. Deterministic for (SEED, date)."""
    d = st.sim_date + timedelta(days=1)
    out = {"weather_daily": [], "pass_status_daily": [], "tempo_daily": [],
           "stock_daily": [], "vehicle_events": [], "consumption_daily": []}
    winter = d.month in (11, 12, 1, 2, 3)

    # ── 1. tempo (Markov, day-seeded) ────────────────────────────────────────
    rt = _rng("tempo", d)
    probs = TEMPO_TRANSITION_PROBS_DAILY[st.tempo]
    st.tempo = str(rt.choice(TEMPO_LEVELS, p=[probs[s] for s in TEMPO_LEVELS]))
    out["tempo_daily"].append({"date": d, "tempo_level": st.tempo,
                                "generator": GENERATOR_TAG})

    # ── 2. WD events: sample each winter season once (year-seeded) ──────────
    if d.month == 12 and d.day == 1 and d.year not in st.wd_sampled_seasons:
        ry = _rng_year("wd", d.year)
        n_ev = int(ry.poisson(WD_EVENTS_PER_WINTER_LAMBDA))
        season_days = (date(d.year + 1, 3, 31) - d).days
        for _ in range(n_ev):
            es = d + timedelta(days=int(ry.integers(0, season_days)))
            st.wd_future.append({
                "start": es.isoformat(),
                "end": (es + timedelta(days=int(ry.integers(
                    WD_EVENT_DURATION_DAYS[0], WD_EVENT_DURATION_DAYS[1] + 1)))).isoformat(),
                "precip_mult": float(ry.uniform(*WD_EVENT_PRECIP_MULT)),
                "temp_drop": float(ry.uniform(*WD_EVENT_TEMP_DROP_C)),
            })
        st.wd_sampled_seasons.append(d.year)
    # activate / expire
    st.wd_active = [e for e in (st.wd_active + [e for e in st.wd_future
                                                 if e["start"] == d.isoformat()])
                    if e["end"] >= d.isoformat()]
    st.wd_future = [e for e in st.wd_future if e["start"] > d.isoformat()]
    wd_intensity = {"Drass": 1.0, "Tangtse": 0.55, "Leh": 0.25}

    # ── 3. weather per post (AR(1) carried, day-seeded shocks) ──────────────
    rw = _rng("weather", d)
    t_mean_by_post: Dict[str, float] = {}
    snow_by_post: Dict[str, float] = {}
    sigma = DAILY_TEMP_NOISE_SIGMA + (DAILY_TEMP_NOISE_WINTER_BOOST if winter else 0.0)
    for pid in ctx.posts.index:
        post = ctx.posts.loc[pid]
        aname = ctx.anchors[pid]
        anchor = get_anchor(aname)
        t_max_c, t_min_c, precip_expected = climatological_day(anchor, d, post["elev_m"])
        shock = rw.normal(0, sigma)
        ns = (DAILY_TEMP_PERSISTENCE * st.noise_state.get(pid, 0.0)
              + np.sqrt(1 - DAILY_TEMP_PERSISTENCE ** 2) * shock)
        st.noise_state[pid] = float(ns)
        t_max, t_min = t_max_c + ns, t_min_c + ns
        wet_p = min(0.50, precip_expected / 2.5)
        precip = 0.0
        if wet_p > 0 and rw.random() < wet_p:
            precip = float(rw.exponential(scale=precip_expected / wet_p))
        is_wd = False
        for e in st.wd_active:
            inten = wd_intensity.get(aname, 0.5)
            pulse = float(rw.uniform(1.5, 7.0)) * (1.0 + (e["precip_mult"] - 1.0) * inten) / 2.5
            precip = max(precip, pulse)
            t_max -= e["temp_drop"] * inten
            t_min -= e["temp_drop"] * inten
            is_wd = True
        t_mean = (t_max + t_min) / 2.0
        is_snow = bool(t_mean < 1.0 and precip > 0.5)
        t_mean_by_post[pid] = t_mean
        snow_by_post[pid] = precip * (1.0 if is_snow else 0.0)
        out["weather_daily"].append({
            "post_id": pid, "date": d, "t_max_c": round(t_max, 2),
            "t_min_c": round(t_min, 2), "t_mean_c": round(t_mean, 2),
            "precip_mm": round(precip, 2), "is_snow": is_snow,
            "is_wd_active": is_wd, "anchor_name": aname,
            "generator": GENERATOR_TAG})

    # ── 4. pass status (seasonal year-seeded; stochastic day-seeded) ────────
    rc = _rng("closure", d)
    # 4a. sample NEXT winter's seasonal closures once we enter October
    for pname, pcfg in ctx.pass_cfg.items():
        if pcfg.get("closure_regime") != "seasonal":
            continue
        wy = d.year if d.month >= 10 else d.year - 1
        if d.month >= 10 and wy not in st.sampled_winters.get(pname, []):
            ry = _rng_year("closure", wy * 100 + hash(pname) % 97)
            jitter = ry.normal(0, pcfg["closure_start_doy_sigma"])
            base = date(wy, 1, 1) + timedelta(
                days=int(pcfg["closure_start_doy_mean"] + jitter) - 1)
            dur = int(np.clip(ry.normal(pcfg["closure_duration_days_mean"],
                                         pcfg["closure_duration_days_sigma"]),
                               pcfg["min_closure_days"], pcfg["max_closure_days"]))
            st.future_closures.append({
                "pass_name": pname, "start": base.isoformat(),
                "end": (base + timedelta(days=dur)).isoformat(),
                "closure_type": "seasonal"})
            st.sampled_winters.setdefault(pname, []).append(wy)
    # activate scheduled
    for fc in [f for f in st.future_closures if f["start"] == d.isoformat()]:
        st.active_closures.append({"pass_name": fc["pass_name"],
                                    "end_date": fc["end"],
                                    "closure_type": fc["closure_type"]})
    st.future_closures = [f for f in st.future_closures if f["start"] > d.isoformat()]
    # expire
    st.active_closures = [c for c in st.active_closures
                           if c["end_date"] >= d.isoformat()]
    closed_today = {c["pass_name"] for c in st.active_closures}
    # 4b. stochastic + interim regimes — daily Bernoulli with snow boost
    for pname, pcfg in ctx.pass_cfg.items():
        if pname in closed_today:
            continue
        regime = pcfg.get("closure_regime")
        if regime == "stochastic":
            rep = ctx.rep_posts.get(pcfg["served_posts_classification"], ["P001"])
            sev = max(snow_by_post.get(p, 0.0) for p in rep)
            p_base = (pcfg["winter_closure_prob_per_day"]
                      if d.month in (11, 12, 1, 2, 3, 4)
                      else pcfg["summer_closure_prob_per_day"])
            p = min(0.95, p_base * SNOW_EVENT_CLOSURE_BOOST) \
                if sev >= SNOW_EVENT_THRESHOLD_MM else p_base
            if rc.random() < p:
                dur = int(rc.integers(*pcfg["closure_duration"]))
                st.active_closures.append({
                    "pass_name": pname,
                    "end_date": (d + timedelta(days=dur)).isoformat(),
                    "closure_type": "stochastic_snow" if sev >= SNOW_EVENT_THRESHOLD_MM
                                    else "stochastic_routine"})
                closed_today.add(pname)
        elif regime == "seasonal":
            ip = pcfg.get("interim_closure_prob_per_day", 0.0)
            if ip > 0 and rc.random() < ip:
                dur = int(rc.integers(*pcfg["interim_closure_duration"]))
                st.active_closures.append({
                    "pass_name": pname,
                    "end_date": (d + timedelta(days=dur)).isoformat(),
                    "closure_type": "interim"})
                closed_today.add(pname)
    for pname in ctx.all_passes:
        out["pass_status_daily"].append({"pass_name": pname, "date": d,
                                          "is_open": pname not in closed_today,
                                          "generator": GENERATOR_TAG})

    # ── 5. isolation per post (same truth consumption + stock both see) ─────
    ps_df = pd.DataFrame(out["pass_status_daily"])
    iso_df = compute_isolation_per_post_day(ctx.world, ps_df)
    iso = iso_df.set_index("post_id")["is_isolated"].to_dict()

    # ── 6. consumption + stock per (post, SKU) ───────────────────────────────
    rcons = _rng("consumption", d)
    rstock = _rng("stock", d)
    # AWS year rollover
    if d.month == 1 and d.day == 1:
        st.aws_year = d.year
        st.aws_remaining = {k: float(v) for k, v in ctx.aws_target.items()}
    if not st.aws_remaining and d.month in AWS_SEASON_MONTHS:
        st.aws_remaining = {k: float(v) for k, v in ctx.aws_target.items()}
    is_aws_day = d.month in AWS_SEASON_MONTHS or (d.month == 10 and d.day <= 10)
    if is_aws_day:
        # crude remaining-open-day estimate without hindsight: calendar days
        # left in the AWS window this year
        rem_days = 0
        for m in AWS_SEASON_MONTHS:
            if m > d.month:
                rem_days += _days_in_month(d.year, m)
            elif m == d.month:
                rem_days += _days_in_month(d.year, m) - d.day + 1
        rem_days += 10 if d.month <= 10 else 0
        rem_days = max(rem_days, 1)

    for pid in ctx.posts.index:
        post = ctx.posts.loc[pid].to_dict()
        post["band"] = ctx.posts.loc[pid]["band"]
        is_iso = bool(iso.get(pid, False))
        t_mean = t_mean_by_post[pid]
        for sku_id in ctx.skus.index:
            sku = ctx.skus.loc[sku_id].to_dict()
            sku["sku"] = sku_id
            key = (pid, sku_id)
            if key not in st.stock:
                continue
            perishable = _is_perishable(int(sku["shelf_life_days"]))
            tier = int(sku["tier"])

            nominal = draw_consumption(rcons, sku, post, t_mean, st.tempo, is_iso)
            # perishable substitution (isolation-gated simple rule)
            consumed = nominal
            if perishable and is_iso:
                sub = PERISHABLE_SUBSTITUTE_MAP.get(sku_id)
                consumed = 0.0
                if sub and (pid, sub) in st.stock:
                    st.setdefault_delta = None  # no-op marker
                    # add displaced demand onto substitute by direct draw-down
                    # handled below via demand_delta dict
            out["consumption_daily"].append({
                "post_id": pid, "sku": sku_id, "date": d,
                "qty_consumed": round(nominal, 3), "tempo": st.tempo,
                "is_isolated": bool(is_iso), "t_mean_c": round(t_mean, 2),
                "generator": GENERATOR_TAG})

            opening = st.stock[key]
            # AWS receipt
            aws_rx = 0.0
            if is_aws_day and not is_iso and st.aws_remaining.get(key, 0.0) > 0:
                aws_rx = min(st.aws_remaining[key] / rem_days, st.aws_remaining[key])
                st.aws_remaining[key] -= aws_rx
            # routine arrivals
            routine_rx = 0.0
            keep = []
            for arr, qty in st.pending.get(key, []):
                if arr == d.isoformat():
                    routine_rx += qty
                elif arr > d.isoformat():
                    keep.append((arr, qty))
            st.pending[key] = keep
            # perishable demand displacement: fresh→substitute while isolated
            delta = 0.0
            if is_iso:
                for fresh, sub in PERISHABLE_SUBSTITUTE_MAP.items():
                    if sub == sku_id and (pid, fresh) in st.stock:
                        f_sku = ctx.skus.loc[fresh].to_dict(); f_sku["sku"] = fresh
                        delta += draw_consumption(
                            _rng("consumption", d), f_sku, post, t_mean,
                            st.tempo, is_iso) * 0.8   # 80% substitution take-up
            consumed = max(0.0, (0.0 if (perishable and is_iso) else nominal) + delta)
            spoil = opening * SPOILAGE_DAILY_FRACTION_PERISHABLE if perishable else 0.0
            available = opening + aws_rx + routine_rx - spoil
            if available >= consumed:
                closing, unmet = available - consumed, 0.0
            else:
                closing, unmet = 0.0, consumed - available
            rate = ctx.rate.get(key, 0.0) or max(consumed, 1e-6)
            doc = closing / rate
            thresh = STOCKOUT_RATIONING_THRESHOLD_DAYS[tier]
            status = ("stockout" if (unmet > 0 or closing <= 0)
                      else "rationing" if doc < thresh else "ok")
            # routine convoy dispatch
            plan_days = ctx.plan_days.get(key, ROUTINE_RECEIPT_REFILL_TO_COVERAGE_DAYS)
            is_pol = str(sku_id).startswith("POL")
            min_gap = POL_CONVOY_MIN_GAP_DAYS if is_pol else ROUTINE_CONVOY_MIN_GAP_DAYS
            lc = st.last_convoy.get(key)
            since = (d - date.fromisoformat(lc)).days if lc else 9999
            if (not is_iso and not st.pending.get(key) and rate > 0
                    and since >= min_gap
                    and (plan_days - doc) > ROUTINE_CONVOY_DISPATCH_GAP_DAYS):
                refill = max(0.0, plan_days * rate - closing)
                if is_pol:
                    refill = min(refill, POL_CONVOY_MAX_REFILL_COVERAGE_DAYS * rate)
                if refill > 0:
                    lat = int(rstock.integers(ROUTINE_RECEIPT_CONVOY_LATENCY_DAYS[0],
                                               ROUTINE_RECEIPT_CONVOY_LATENCY_DAYS[1] + 1))
                    st.pending.setdefault(key, []).append(
                        ((d + timedelta(days=lat)).isoformat(), float(refill)))
                    st.last_convoy[key] = d.isoformat()
            st.stock[key] = float(closing)
            out["stock_daily"].append({
                "post_id": pid, "sku": sku_id, "date": d,
                "opening_stock": round(opening, 3), "aws_receipt": round(aws_rx, 3),
                "routine_receipt": round(routine_rx, 3),
                "nominal_consumption": round(nominal, 3),
                "consumption": round(consumed, 3), "spoilage": round(spoil, 3),
                "unmet_demand": round(unmet, 3), "closing_stock": round(closing, 3),
                "days_of_cover": round(doc, 2), "status": status,
                "generator": GENERATOR_TAG})

    # ── 7. vehicles (memoryless hazard, day-seeded) ──────────────────────────
    rv = _rng("vehicle", d)
    pass_open_today = {p: (p not in closed_today) for p in ctx.all_passes}
    any_closed = any(not v for v in pass_open_today.values())
    mission_p = (MISSIONS_PER_MONTH_WINTER if winter else MISSIONS_PER_MONTH_OPEN) / 30.0
    lookup = {(p, d): pass_open_today[p] for p in ctx.all_passes}
    for vid in ctx.vehicles.index:
        v = st.veh[vid]
        if v["repair_until"]:
            if d.isoformat() >= v["repair_until"]:
                v["repair_until"] = None
            else:
                continue
        if rv.random() < mission_p:
            scale = float(ctx.vehicles.loc[vid]["weibull_scale_days"])
            v["cum"] += ctx.duty[vid] * daily_hazard_increment(
                rv, d, lookup, ctx.all_passes, scale, ctx.band_mix[vid])
            if v["cum"] >= v["thr"]:
                if rv.random() < DEADLINE_REQUIRES_DEPOT_PROB:
                    rd = int(rv.integers(*REPAIR_TIME_DEPOT_DAYS)); loc = "depot"
                else:
                    rd = int(rv.integers(*REPAIR_TIME_FIELD_DAYS)); loc = "field"
                ret = d + timedelta(days=rd)
                out["vehicle_events"].append({
                    "vehicle_id": vid,
                    "vehicle_class": ctx.vehicles.loc[vid]["vehicle_class"],
                    "deadline_date": d, "return_date": ret, "repair_days": rd,
                    "repair_location": loc, "winter_flag": winter,
                    "generator": GENERATOR_TAG})
                v["repair_until"] = ret.isoformat()
                v["cum"] = 0.0
                v["thr"] = float(sample_event_threshold(rv)) * 0.85

    st.sim_date = d
    return out


# ═════════════════════════════════════════════════════════════════════════════
# Orchestration: advance N days, persist live tables, materialize for Stage 3
# ═════════════════════════════════════════════════════════════════════════════
_LIVE_TABLES = ["weather_daily", "pass_status_daily", "tempo_daily",
                "stock_daily", "vehicle_events", "consumption_daily"]


def advance_to(target: date, state_dir: Path = WORLD_STATE_DIR,
               data_dir: Path = DATA_DIR, verbose: bool = True) -> WorldState:
    """Advance the world state to `target` (inclusive). Initialises state at
    the canonical boundary if none exists. Appends per-day rows to
    live_<table>.parquet under state_dir."""
    ctx = Ctx(data_dir)
    if (state_dir / "state.json").exists():
        st = WorldState.load(state_dir)
    else:
        st = init_state(ctx, data_dir)
        if verbose:
            print(f"[advance] initialised state at canonical boundary {st.sim_date}")
    if target <= st.sim_date:
        if verbose:
            print(f"[advance] already at {st.sim_date} ≥ {target} — nothing to do")
        return st

    buf = {t: [] for t in _LIVE_TABLES}
    n = 0
    while st.sim_date < target:
        day_rows = advance_one_day(ctx, st)
        for t in _LIVE_TABLES:
            buf[t].extend(day_rows[t])
        n += 1
    # append to live parquets
    state_dir.mkdir(exist_ok=True, parents=True)
    for t in _LIVE_TABLES:
        if not buf[t]:
            continue
        new = pd.DataFrame(buf[t])
        live_p = state_dir / f"live_{t}.parquet"
        if live_p.exists():
            old = pd.read_parquet(live_p)
            # idempotency: drop any overlap (re-advance after restart)
            new = pd.concat([old, new], ignore_index=True)
            sub = [c for c in ("post_id", "sku", "pass_name", "vehicle_id", "date")
                   if c in new.columns]
            new = new.drop_duplicates(subset=sub, keep="last")
        new.to_parquet(live_p, index=False)
    st.save(state_dir)
    if verbose:
        print(f"[advance] advanced {n} day(s) → sim_date {st.sim_date}")
    return st


def materialize_live_data(out_dir: Path, state_dir: Path = WORLD_STATE_DIR,
                           data_dir: Path = DATA_DIR) -> Path:
    """Build a complete Stage-3-ready data dir: canonical base ∪ continuation.
    Point BASTION_DATA_DIR here and Stages 3-4 run unchanged."""
    out_dir.mkdir(exist_ok=True, parents=True)
    static = ["posts", "routes", "skus", "vehicles", "post_distances", "aws_plan",
              "pass_closures", "wd_events"]
    for t in static:
        src = data_dir / f"{t}.parquet"
        if src.exists():
            shutil.copy2(src, out_dir / f"{t}.parquet")
    for t in _LIVE_TABLES:
        base_p = data_dir / f"{t}.parquet"
        live_p = state_dir / f"live_{t}.parquet"
        frames = []
        if base_p.exists():
            frames.append(pd.read_parquet(base_p))
        if live_p.exists():
            live = pd.read_parquet(live_p)
            live = live.drop(columns=["generator"], errors="ignore")
            frames.append(live)
        if frames:
            allf = pd.concat(frames, ignore_index=True)
            allf.to_parquet(out_dir / f"{t}.parquet", index=False)
    return out_dir


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Advance the synthetic world")
    ap.add_argument("--to", type=str, required=True, help="target date YYYY-MM-DD")
    ap.add_argument("--materialize", type=str, default=None,
                    help="optional dir to materialize a Stage-3-ready dataset")
    args = ap.parse_args()
    st = advance_to(date.fromisoformat(args.to))
    if args.materialize:
        p = materialize_live_data(Path(args.materialize))
        print(f"[advance] materialized live dataset → {p}")
